### ISSUE TITLE
Selecting more than 10 locations with listview.

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#514]
The listview module throws following error upon selection with 10 locations already in the listview.

```
listview.mjs:96 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'hook')
    at Object.set (listview.mjs:96:14)
    at Object.St [as get] (get.mjs:63:17)
```

**Comment by dbauszus-glx** [comment]
An alert should be shown when locations can not be added to the listview.

https://github.com/GEOLYTIX/xyz/pull/515
